---
  - hosts: all
    gather_facts: yes
    remote_user: vagrant

    tasks:
    - name: Actualizar paquetes y cache del sistema
      become: yes
      apt: 
        update_cache: yes

    - name: Instalacion de npm
      become: yes
      apt: 
        name: npm
        state: present

    - name: Instalacion de node via n (npm)
      become: yes
      command: npm install -g n

    - name: Actualizacion de node a la ultima version
      become: yes
      command: n latest

    - name: Instalacion de los paquetes necesarios de node a traves de npm en package.json
      npm:
        path: /home/vagrant/Billboard-IV
        production: yes
        state: latest

    - name: Instalacion de nodemon de forma global
      become: yes
      npm:
        name: nodemon
        global: yes
  